apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: kube-pod-in-host-info
    kubernetes.io/cluster-service: "true"
    name: kube-pod-in-host-info
    tier: node
  name: kube-pod-in-host-info
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: kube-pod-in-host-info
      k8s-app: kube-pod-in-host-info
      kubernetes.io/cluster-service: "true"
      name: kube-pod-in-host-info
      tier: node
  template:
    metadata:
      labels:
        component: kube-pod-in-host-info
        k8s-app: kube-pod-in-host-info
        kubernetes.io/cluster-service: "true"
        name: kube-pod-in-host-info
        tier: node
    spec:
      hostNetwork: true
      containers:
      - name: kube-pod-in-host-info
        image: ylck/host-pod-info 
        imagePullPolicy: Always
        ports:
        - containerPort: 8088
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-name
          mountPath: /etc/hostname
        - name: docker-socket
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
      - name: host-name
        hostPath:
          path: /etc/hostname
---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: kube-pod-in-host-info
    k8s-app: kube-pod-in-host-info
    kubernetes.io/cluster-service: "true"
    name: kube-pod-in-host-info
    tier: node
  name: kube-pod-in-host-info
  namespace: kube-system
spec:
  ports:
  - name: metrics
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
     k8s-app: kube-pod-in-host-info
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-pod-info
  namespace: monitoring
  labels:
    team: frontend
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      k8s-app: kube-pod-in-host-info
  endpoints:
    - port: metrics
